#!/bin/bash
Humidity="`/home/telegraf/bme280_text.py |awk '{ if ($1 == "Humidity") { print substr($3,1,6) } }' 2>>~/temp_err.txt`"
#cat /home/telegraf/temperature12 > ~/temp.txt 2>~/temp_err.txt
echo $Humidity
#echo 18
